'use client';

import React, { useState } from 'react';
import { useData } from '@/context/DataContext';
import {
  Printer,
  FileText,
  Download,
  X,
  Sparkles,
  CheckCircle2,
  TrendingUp,
  AlertTriangle,
  Building2,
  User,
  Copy,
  Check,
  ShieldCheck
} from 'lucide-react';

interface ExecutiveReportModalProps {}

export const ExecutiveReportModal: React.FC<ExecutiveReportModalProps> = () => {
  const { currentDataset, filteredDataset, isReportModalOpen, setIsReportModalOpen } = useData();
  const isOpen = isReportModalOpen;
  const onClose = () => setIsReportModalOpen(false);

  const dataset = filteredDataset || currentDataset;

  const [companyName, setCompanyName] = useState('Acme Global Holdings');
  const [preparedBy, setPreparedBy] = useState('DataPulse AI Executive Analyst');
  const [reportTitle, setReportTitle] = useState('Executive Data Intelligence Report');
  const [copied, setCopied] = useState(false);

  if (!isOpen || !dataset) return null;

  const numericCols = dataset.columns.filter((c) => c.type === 'numeric' && !c.isIdColumn);
  const catCols = dataset.columns.filter((c) => c.type === 'categorical' || c.type === 'text');
  const primaryMetric = numericCols[0] || dataset.columns[0];
  const primaryCat = catCols[0];

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = `
# ${reportTitle}
**Organization:** ${companyName}
**Prepared By:** ${preparedBy}
**Date:** ${new Date().toLocaleDateString(undefined, { dateStyle: 'long' })}
**Source Dataset:** ${dataset.fileName} (${dataset.rowCount.toLocaleString()} records, ${dataset.columnCount} attributes)
**Data Quality Score:** ${dataset.qualityScore}/100

---

## 1. Executive Summary
This executive briefing presents a consolidated analysis of **${dataset.fileName}**. 
The dataset consists of **${dataset.rowCount.toLocaleString()} rows** across **${dataset.columnCount} columns**, representing an overall data hygiene score of **${dataset.qualityScore}%**.

${
  primaryMetric && primaryMetric.sum !== undefined
    ? `- **Primary Aggregate (${primaryMetric.name}):** Total of ${primaryMetric.sum.toLocaleString()} (Mean: ${primaryMetric.mean}, Min: ${primaryMetric.min}, Max: ${primaryMetric.max})`
    : ''
}

---

## 2. Strategic Insights & Detected Anomalies
${dataset.insights.map((ins, i) => `${i + 1}. **${ins.title}** (${ins.importance.toUpperCase()}): ${ins.description}`).join('\n')}

---

## 3. Key Categorical Distributions
${
  primaryCat && primaryCat.topCategories
    ? primaryCat.topCategories.map((c) => `- **${c.value}**: ${c.count.toLocaleString()} occurrences (${c.percentage}%)`).join('\n')
    : 'No major categorical distributions identified.'
}

---
*Generated by DataPulse AI Analyst Pro*
`.trim();

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-2 sm:p-4 overflow-y-auto">
      <div className="w-full max-w-4xl my-auto space-y-4">
        {/* Top Control Bar (Hidden during Print) */}
        <div className="p-4 rounded-2xl bg-slate-900 border border-white/10 flex flex-col sm:flex-row items-center justify-between gap-3 print:hidden">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-gradient-to-tr from-cyan-500 to-violet-600 text-white shadow-md">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white">
                Executive PDF Report Preview
              </h3>
              <p className="text-xs text-slate-400">
                Ready for C-suite presentation or direct browser &quot;Save as PDF&quot;
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 self-stretch sm:self-auto justify-end">
            <button
              onClick={handleCopyMarkdown}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-white/10 transition"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4 text-cyan-400" />}
              <span>{copied ? 'Copied MD' : 'Copy MD'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-teal-400 hover:from-cyan-400 hover:to-teal-300 text-slate-950 font-bold text-xs shadow-lg transition"
            >
              <Printer className="w-4 h-4" />
              <span>Print / Save as PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 border border-white/10 transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Customization Inputs (Hidden during Print) */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 print:hidden text-xs">
          <input
            type="text"
            value={reportTitle}
            onChange={(e) => setReportTitle(e.target.value)}
            placeholder="Report Title"
            className="bg-slate-900/80 border border-slate-700 rounded-xl px-3 py-2 text-white placeholder-slate-500 focus:outline-none focus:border-cyan-400"
          />
          <input
            type="text"
            value={companyName}
            onChange={(e) => setCompanyName(e.target.value)}
            placeholder="Company Name"
            className="bg-slate-900/80 border border-slate-700 rounded-xl px-3 py-2 text-white placeholder-slate-500 focus:outline-none focus:border-cyan-400"
          />
          <input
            type="text"
            value={preparedBy}
            onChange={(e) => setPreparedBy(e.target.value)}
            placeholder="Prepared By"
            className="bg-slate-900/80 border border-slate-700 rounded-xl px-3 py-2 text-white placeholder-slate-500 focus:outline-none focus:border-cyan-400"
          />
        </div>

        {/* PRINTABLE DOCUMENT CONTAINER */}
        <div
          id="printable-executive-report"
          className="bg-white text-slate-900 p-8 sm:p-12 rounded-2xl shadow-2xl max-h-[75vh] overflow-y-auto print:max-h-none print:overflow-visible print:p-0 print:shadow-none print:m-0 space-y-8"
        >
          {/* Document Cover Header */}
          <div className="border-b-2 border-slate-900 pb-6 flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-[10px] font-extrabold uppercase tracking-widest px-2.5 py-0.5 rounded bg-slate-900 text-white">
                  CONFIDENTIAL EXECUTIVE BRIEFING
                </span>
                <span className="text-[10px] font-bold text-slate-500">
                  DataPulse AI Analyst Pro
                </span>
              </div>
              <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900">
                {reportTitle}
              </h1>
              <p className="text-xs text-slate-600 mt-1 font-medium">
                Prepared for <span className="font-bold text-slate-900">{companyName}</span> • Prepared by {preparedBy}
              </p>
            </div>

            <div className="text-left sm:text-right text-xs text-slate-600 space-y-0.5 shrink-0">
              <div className="font-bold text-slate-900">
                {new Date().toLocaleDateString(undefined, { dateStyle: 'long' })}
              </div>
              <div>File: <span className="font-semibold text-slate-800">{dataset.fileName}</span></div>
              <div className="flex items-center gap-1.5 sm:justify-end">
                <span className="inline-block w-2 h-2 rounded-full bg-emerald-500"></span>
                <span>Quality Score: <b>{dataset.qualityScore}/100</b></span>
              </div>
            </div>
          </div>

          {/* Section 1: Executive Summary */}
          <div className="space-y-3">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 pb-1">
              <span className="w-2 h-2 rounded bg-cyan-600 inline-block"></span>
              1. Executive Overview & Data Scope
            </h2>
            <p className="text-xs text-slate-700 leading-relaxed font-normal">
              This report synthesizes the structural and statistical dimensions of <b>{dataset.fileName}</b>. 
              The dataset contains a total of <b>{dataset.rowCount.toLocaleString()} validated records</b> structured across <b>{dataset.columnCount} dimensional attributes</b> ({numericCols.length} numerical metrics and {catCols.length} categorical dimensions).
              Overall data completeness and statistical validity is rated at <b>{dataset.qualityScore}%</b>.
            </p>
          </div>

          {/* Section 2: Key Metric Scorecard */}
          <div className="space-y-3">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 pb-1">
              <span className="w-2 h-2 rounded bg-violet-600 inline-block"></span>
              2. Core Performance Scorecard
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-1">
                <span className="text-[11px] font-semibold text-slate-500">Total Records</span>
                <div className="text-xl font-extrabold text-slate-900">{dataset.rowCount.toLocaleString()}</div>
                <span className="text-[10px] text-slate-500">Validated rows</span>
              </div>

              {primaryMetric && (
                <>
                  <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-1">
                    <span className="text-[11px] font-semibold text-slate-500">Mean {primaryMetric.name}</span>
                    <div className="text-xl font-extrabold text-slate-900">
                      {primaryMetric.mean !== undefined ? primaryMetric.mean.toLocaleString() : 'N/A'}
                    </div>
                    <span className="text-[10px] text-slate-500">Median: {primaryMetric.median || 'N/A'}</span>
                  </div>

                  <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-1">
                    <span className="text-[11px] font-semibold text-slate-500">Aggregate {primaryMetric.name}</span>
                    <div className="text-xl font-extrabold text-slate-900">
                      {primaryMetric.sum !== undefined ? primaryMetric.sum.toLocaleString() : 'N/A'}
                    </div>
                    <span className="text-[10px] text-slate-500">Total calculated sum</span>
                  </div>

                  <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-1">
                    <span className="text-[11px] font-semibold text-slate-500">Peak {primaryMetric.name}</span>
                    <div className="text-xl font-extrabold text-slate-900">
                      {primaryMetric.max !== undefined ? primaryMetric.max.toLocaleString() : 'N/A'}
                    </div>
                    <span className="text-[10px] text-slate-500">Min: {primaryMetric.min || '0'}</span>
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Section 3: Strategic Insights & Anomalies */}
          <div className="space-y-3">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 pb-1">
              <span className="w-2 h-2 rounded bg-emerald-600 inline-block"></span>
              3. Strategic Insights & Anomaly Detections
            </h2>
            <div className="space-y-2.5">
              {dataset.insights.map((ins, idx) => (
                <div
                  key={idx}
                  className="p-3.5 rounded-xl border border-slate-200 bg-slate-50/70 text-xs flex items-start gap-3"
                >
                  <span className="w-5 h-5 rounded-full bg-slate-900 text-white font-bold text-[10px] flex items-center justify-center shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-slate-900">{ins.title}</span>
                      <span className="text-[9px] font-extrabold uppercase px-2 py-0.5 rounded bg-slate-200 text-slate-700">
                        {ins.type}
                      </span>
                    </div>
                    <p className="text-slate-600 leading-relaxed">{ins.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 4: Categorical Distribution Table */}
          {primaryCat && primaryCat.topCategories && (
            <div className="space-y-3">
              <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 pb-1">
                <span className="w-2 h-2 rounded bg-teal-600 inline-block"></span>
                4. Primary Segmentation Breakdown ({primaryCat.name})
              </h2>
              <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
                <thead className="bg-slate-100 border-b border-slate-200">
                  <tr>
                    <th className="p-2.5 font-bold text-slate-900">Category Value</th>
                    <th className="p-2.5 font-bold text-slate-900 text-right">Record Count</th>
                    <th className="p-2.5 font-bold text-slate-900 text-right">Share (%)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {primaryCat.topCategories.map((c, i) => (
                    <tr key={i}>
                      <td className="p-2.5 font-semibold text-slate-800">{c.value}</td>
                      <td className="p-2.5 text-slate-700 text-right">{c.count.toLocaleString()}</td>
                      <td className="p-2.5 text-slate-700 text-right font-bold">{c.percentage}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Section 5: Data Hygiene & Quality Verification */}
          <div className="space-y-3 pt-2">
            <h2 className="text-sm font-extrabold text-slate-900 uppercase tracking-wider flex items-center gap-2 border-b border-slate-200 pb-1">
              <span className="w-2 h-2 rounded bg-amber-500 inline-block"></span>
              5. Data Governance & Hygiene Verification
            </h2>
            <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 text-xs space-y-2">
              <div className="flex items-center justify-between">
                <span className="font-semibold text-slate-700">Governance Integrity Score:</span>
                <span className="font-bold text-emerald-600">{dataset.qualityScore}/100 Grade A</span>
              </div>
              <p className="text-[11px] text-slate-600 leading-relaxed">
                All dimensional headers and numerical ranges were evaluated for schema uniformity.
                Statistical anomalies were isolated and documented. This dataset is declared certified for downstream presentation and decision modeling.
              </p>
            </div>
          </div>

          {/* Document Sign-off Footer */}
          <div className="pt-8 border-t border-slate-200 flex flex-col sm:flex-row items-start sm:items-center justify-between text-[11px] text-slate-500 gap-2">
            <div className="flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-emerald-600" />
              <span>Certified by DataPulse AI Automated Intelligence Engine</span>
            </div>
            <div>Generated: {new Date().toISOString()}</div>
          </div>
        </div>
      </div>
    </div>
  );
};
